# Generated by Django 4.2 on 2023-06-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('En progreso', 'En progreso'), ('Finalizado', 'Finalizado')], default='Nuevo', max_length=20),
        ),
    ]
