# Generated by Django 4.2 on 2023-06-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='queryType',
            new_name='query_type',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='featured',
            new_name='is_featured',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='new',
            new_name='is_new',
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('En progreso', 'En progreso'), ('Finalizado', 'Finalizado')], default='En progreso', max_length=20),
        ),
    ]
