# Generated by Django 4.2 on 2023-06-12 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rentalorder_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalorder',
            name='order_number',
        ),
    ]
