# Generated by Django 4.2 on 2023-06-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_querytype_contact_query_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='rentables',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='is_rentable',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='RentableProduct',
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
