# Generated by Django 4.2 on 2023-04-26 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_querytipe_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QueryTipe',
            new_name='QueryType',
        ),
    ]
