# Generated by Django 4.2 on 2023-05-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_querytipe_contact_querytype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cc',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='categorys'),
        ),
    ]
