# Generated by Django 4.2 on 2023-05-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='rental_product',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='product',
        ),
        migrations.AddField(
            model_name='rental',
            name='barrels',
            field=models.ManyToManyField(to='app.barrel'),
        ),
    ]
