# Generated by Django 4.2 on 2023-05-26 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_barrel_remove_product_rental_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Barrel',
            new_name='Rentable',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='barrels',
            new_name='rentables',
        ),
    ]
