# Generated by Django 4.2 on 2023-06-11 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0019_order_capture_id_alter_order_fecha_creacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_clp',
            new_name='accumulated',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='apellido',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='capture_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='order',
            name='telefono',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
