# Generated by Django 4.2 on 2023-06-11 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_total_clp_order_accumulated_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
