# Generated by Django 4.2 on 2023-06-11 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_name',
            new_name='name',
        ),
    ]
