# Generated by Django 4.2 on 2023-06-11 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_price',
        ),
    ]
