# Generated by Django 4.2 on 2023-06-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_rename_adress_order_address_remove_order_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pagado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
