# Generated by Django 4.2 on 2023-06-11 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_order_fecha_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
